---
abstract: 'Module to convert an exported Cadsoft Eagle CSV to XLS'
author:
  - 'Lieven Hollevoet <hollie@cpan.org>'
build_requires:
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-BomCsv2Xls
requires:
  Carp: '0'
  Excel::Writer::XLSX: '0'
  Getopt::Long: '0'
  Moose: '0'
  Pod::Usage: '0'
  Text::CSV: '0'
  autodie: '0'
  constant: '0'
  namespace::autoclean: '0'
  perl: '5.018'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/hollie/app-bomcsv2xls-perl/issues
  repository: git://github.com/hollie/app-bomcsv2xls-perl.git
version: '0.02'
